#!/bin/bash

############################################

function rekt()
{
  mkdir temp
  cd temp/
  git init
  cd ../

  for branch in $(git branch | cut -c3-)
  do
    cd temp/
    git checkout --orphan "$branch"
    cd ../
    git checkout "$branch"
    cp -r ./* temp/
    cd temp/
    git add ./*
    cd ../
  done

  cd temp/
  rm -rf temp/ #For some reason it nests temp directories...
  git commit -am "Git rekt"
  cd ../

  for file in $(ls -a)
  do
    if [ "$file" != "temp" ]
    then
      rm -rf "$file"
    fi
  done
}

############################################
############################################

echo -n "You want git rekt? [y/n]"
read input

if [ "$input" == "y" ]
then
  rekt
  echo "Consider yourself rekt."
else
  echo "Chicken exit's right over here for you."
fi
