#!/bin/bash

############################################

function rekt()
{
  dir=$(pwd)
  mkdir temp
  cd temp/
  git init
  cd ../

  for branch in $(git branch)
  do
  	if [ "$branch" != "*" ]
  	then
  	  cd temp/
  	  git checkout --orphan "$branch"
  	  cd ../
      git checkout "$branch"
      mv ./* temp/
    fi
  done

  rm -r .git
  mv temp/* ./*
  git commit -am "Git rekt, Mr. Repository."
  rmdir temp
}

############################################
############################################

echo -n "You want git rekt? [y/n]"
read input

if [ "$input" == "y" ]
then
  rekt
  echo "Consider yourself rekt."
else
  echo "Chicken exit's right over here for you."
fi
